azs:
- name: z1
  cloud_properties:
    datacenters:
    - name: vcpi-dc 
      clusters: ['vcpi-cluster-1': {}, 'vcpi-cluster-2': {}]

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: default
  type: manual
  managed: true
  subnets:
  - range: '192.168.111.0/24'
    gateway: '192.168.111.1'
    azs: [z1]
    dns: [8.8.8.8]
    reserved: [192.168.111.3]
    cloud_properties:
      vds: 'vcpi-switch-1' 

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
